- name: installing python 3.6
  ansible.builtin.package:
    name: {{item}}
    state: 
  loop: 
    - python36 
    - gcc 
    - python3-devel

- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup


- name: downloading dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
    



